### ISSUE TITLE
So when i try to use the fifomm one it just crashes when adding a player to the queue

### ISSUE THREAD

**Issue by Pliexe** [Luifr/matchmaking#2]
So basically when a player gets pushed into the matchmaking class thingy it crashes with this error

`C:\Users\-\Desktop\Ecard server\node_modules\matchmaking\javascript\matchMaker.js:15            let playerKey = this.getKey(player);
                                 ^

TypeError: this.getKey is not a function
    at FifoMatchmaker.Matchmaker.indexOnQueue (C:\Users\-\Desktop\Ecard server\node_modules\matchmaking\javascript\matchMaker.js:15:34)
    at FifoMatchmaker.Matchmaker.push (C:\Users\-\Desktop\Ecard server\node_modules\matchmaking\javascript\matchMaker.js:10:22)
    at Socket.<anonymous> (C:\Users\-\Desktop\Ecard server\server.js:25:21)
    at Socket.emit (events.js:210:5)
    at C:\Users\-\Desktop\Ecard server\node_modules\socket.io\lib\socket.js:528:12
    at processTicksAndRejections (internal/process/task_queues.js:75:11)`

**Comment by Pliexe** [comment]
Found what was the issue and it was due to bad documentation, I suggest fixing your documentation so people don't get confused

**Comment by Pliexe** [comment]
Found what was the issue and it was due to bad documentation, I suggest fixing your documentation so people don't get confused
